config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do    
    resources :doses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, :image_url, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    def index #all tasks 
      @cocktails = Cocktail.all
    end
    
    def show
       @cocktail = Cocktail.find(params[:id])
    end

    def new
      @cocktail = Cocktail.new
    end

    def create
      @cocktail = Cocktail.new(cocktail_params)
      @cocktail.save
      redirect_to cocktails_path( @cocktail )
    end
    
      private
    
    def edit
      @cocktail = Cocktail.find(params[:id])
    end

    def update
      @cocktail = Cocktail.find(params[:id])
      @cocktail.update(cocktail_params)
      redirect_to cocktails_path( @cocktail )
    end

    def destroy
      @cocktail = Cocktail.find(params[:id])
      @cocktail.destroy!
      redirect_to cocktails_path( @cocktail )
    end

    def cocktail_params
      params.require(:cocktail ).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :find_cocktail, only: [:new, :create]
    def new
        @dose = Dose.new
      end
    
    def edit
    @dose = Dose.find(params[:id])
    end

    def create
      @dose = Dose.new(dose_params)
      @dose.cocktail = @cocktail 
      if @dose.save
        redirect_to cocktail_path( @cocktail )
      else
        render :new
    end
    end

    def update
    @dose = Dose.find(params[:id])
    @dose.update(dose_params)
    redirect_to cocktail_path( @dose )
    end

    def destroy
    @dose = Review.find(params[:id])
    @dose.destroy!
    redirect_to cocktail_path( @dose.cocktail ) 
    end
    
    private

    def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1> John's Cocktail Bar </h1>

<%= cl_image_tag("tfyizpsoxh6vc2kequzi",
      width: 400, height: 300, crop: :fill) %>

<br>
       
<% @cocktails.each do |cocktail| %>
<img src= <%= cocktail.image_url %> alt="cocktail" width="300" height="250">
<h2><%= link_to cocktail.name, cocktail_path(cocktail.id) %> 
</h2>
<% end %>

<%= link_to 'Add new cocktail', new_cocktail_path(@cocktail) %>
<!-- link to create a new cocktail -->

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name, prompt: "name of cocktail" %>
  <%= f.input :image_url, prompt: "put image_url here" %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<%= cl_image_tag("tfyizpsoxh6vc2kequzi",
      width: 800, height: 600, crop: :fill) %>

<p>
<strong>Name:</strong>
<%= @cocktail.name %>
</p>

<p>
<strong>recipe:</strong> 
<% @cocktail.doses.each do |dose| %>
<%= dose.description %>
<%= dose.ingredient.name %>
<% end %>
</p>

<%= link_to 'Delete', cocktail_path(@cocktail), method: :delete %>
<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %> |
<%= link_to 'Add a new recipe', new_cocktail_dose_path(@cocktail) %>

app/views/doses/edit.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :name %>
  <%= f.association :name, collection: Ingredient.active.order(:name), prompt: "Choose an Ingredient" %>
  <%= f.association :description, collection: Dose.active.order(:description), prompt: "Choose a dosage" %>
  <%= f.button :submit %>
<% end %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, collection: Ingredient.order(:name), prompt: "Choose an Ingredient" %>
  <%= f.input :description, prompt: "Choose a dosage" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>